[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/nbrg-ppcu/prokbert/blob/development/examples/sequence_dataset.ipynb)

# Working with sequence and embedding datasets

This notebook shows how to store many contigs as **one concatenated sequence plus metadata**, and how to look up sequences and embeddings by contig and coordinate. It has 4 steps:

1. Loading contigs from a FASTA file
2. Building, saving and loading a `SequenceDataset`
3. Querying sequences by ID, coordinate and orientation
4. Looking up embeddings with an `EmbeddingDataset`

We use a tiny dataset: the first contigs of the extremophile phage dataset, truncated to 20–30 nucleotides, so every result can be checked manually.

## Setting up the environment

The examples run on a CPU, so no GPU is needed. Install ProkBERT from GitHub:

In [1]:
# run this cell if necessary, to install prokbert lib
# !pip install git+https://github.com/nbrg-ppcu/prokbert.git@development --quiet

In [2]:
import os
import yaml
import math
import logging
import requests

import torch
import pandas as pd

from prokbert import helper
from prokbert.sequence_dataset import SequenceDataset, EmbeddingDataset

In [3]:
logging.basicConfig(level=logging.DEBUG, format="%(message)s")

## Preparing the dataset

You can either use your own FASTA file (set `DATA_PATH` to it) or use the small test file from the ProkBERT repository. The code below uses the local file if it exists, and downloads it otherwise (for example in Colab).

The file contains 3 *Aeromonas* phage contigs, truncated to 30, 25 and 20 nucleotides.

In [4]:

DATA_PATH = "/home/osvathm/prokbert/tests/data/extremophiles_mini.fasta"
DATA_URL = (
    "https://raw.githubusercontent.com/nbrg-ppcu/prokbert/development/"
    "tests/data/extremophiles_mini.fasta"
)

if not os.path.exists(DATA_PATH):
    os.makedirs(os.path.dirname(DATA_PATH), exist_ok=True)
    response = requests.get(DATA_URL, timeout=30)
    response.raise_for_status()
    with open(DATA_PATH, "w") as f:
        f.write(response.text)

# print(open(DATA_PATH).read())

## 1. Loading contigs

`load_contigs` reads one or more FASTA files (plain or `.gz`) and returns one record per contig, with its ID, sequence (uppercase), orientation and description.

`convert_to` turns the records into a pandas `DataFrame` or a Hugging Face `Dataset`, which is handy for inspection.

In [5]:
seq_ds = SequenceDataset()

In [6]:
contigs = seq_ds.load_contig(DATA_PATH)
# same as above just with multiple files
# contigs = seq_ds.load_contigs([DATA_PATH, DATA_PATH])
helper.convert_to(contigs, format="pandas")

,genome_id,contig_id,sequence,orientation,description
0,None,OM913597.1,TCTCGACCCGTCCCACCGCAATCGCCCCCA,forward,"OM913597.1 Aeromonas phage vB_AspA_Bolek, synt..."
1,None,OM913598.1,TCTCGACCCGCCCCACCGCAACCT,forward,"OM913598.1 Aeromonas phage vB_AspA_Lolek, synt..."
2,None,OM913599.1,CTCGCCTCGCCTCGCTTTCA,forward,"OM913599.1 Aeromonas phage vB_AspA_Tola, synth..."
3,None,OQ832096.1,ACGTNACGTNGGATCCTTAAA,forward,"OQ832096.1 Halomonas phage vB_HmeY_H4907, synt..."
4,None,JX507079.1,GATTACTCGCCTCGCCTCGC,forward,"JX507079.1 Acidithiobacillus phage AcaML1, syn..."

## 2. Building the dataset

`create_dataset` concatenates all contigs into **one long string** (`seq_ds.sequence`) and stores, for each contig, where it starts and ends in that string (`coordinate`, a half-open interval `[start, end)`, like Python slicing).

Why one string? It makes position-based operations simple: sampling a random window from the whole dataset, memory-mapping the sequence from disk, or finding which contig a position belongs to.

In [7]:
seq_ds.create_dataset([DATA_PATH])

In [8]:
print("Total length:", len(seq_ds.sequence))
print(seq_ds.sequence)

Total length: 115
TCTCGACCCGTCCCACCGCAATCGCCCCCATCTCGACCCGCCCCACCGCAACCTCTCGCCTCGCCTCGCTTTCAACGTNACGTNGGATCCTTAAAGATTACTCGCCTCGCCTCGC

In [9]:
pd.DataFrame(seq_ds.metadata)

,genome_id,contig_id,sequence_id,coordinate,orientation,description,label
0,None,OM913597.1,0,"(0, 30)",forward,"OM913597.1 Aeromonas phage vB_AspA_Bolek, synt...",None
1,None,OM913598.1,1,"(30, 54)",forward,"OM913598.1 Aeromonas phage vB_AspA_Lolek, synt...",None
2,None,OM913599.1,2,"(54, 74)",forward,"OM913599.1 Aeromonas phage vB_AspA_Tola, synth...",None
3,None,OQ832096.1,3,"(74, 95)",forward,"OQ832096.1 Halomonas phage vB_HmeY_H4907, synt...",None
4,None,JX507079.1,4,"(95, 115)",forward,"JX507079.1 Acidithiobacillus phage AcaML1, syn...",None

Each contig's slice of the concatenated sequence gives back exactly the original contig:

In [10]:
for meta in seq_ds.metadata:
    start, end = meta["coordinate"]
    print(f"{meta['contig_id']:12} [{start:3}, {end:3})  {seq_ds.sequence[start:end]}")

OM913597.1   [  0,  30)  TCTCGACCCGTCCCACCGCAATCGCCCCCA
OM913598.1   [ 30,  54)  TCTCGACCCGCCCCACCGCAACCT
OM913599.1   [ 54,  74)  CTCGCCTCGCCTCGCTTTCA
OQ832096.1   [ 74,  95)  ACGTNACGTNGGATCCTTAAA
JX507079.1   [ 95, 115)  GATTACTCGCCTCGCCTCGC

### Saving and loading

The sequence is saved as a NumPy array (1 byte per nucleotide), and the metadata as JSON. Loading them back gives the same dataset without parsing the FASTA again.

In [11]:
SAVE_DIR = "outputs/toy_example"
seq_ds.create_dataset([DATA_PATH], save_dir=SAVE_DIR)

loaded_ds = SequenceDataset()
loaded_ds.load_dataset(SAVE_DIR, to_string=True)

assert loaded_ds.sequence == seq_ds.sequence

Dataset saved to 'outputs/toy_example'.

In [12]:
loaded_ds = SequenceDataset()
loaded_ds.load_dataset(SAVE_DIR, to_string=False)

assert loaded_ds.sequence.tobytes().decode("ascii") == seq_ds.sequence

print(os.listdir(SAVE_DIR))

['sequence.npy', 'metadata.json', 'config.yaml', 'embeddings_forward.pt', 'seq_tokens.pt']

## 3. Querying sequences

### From sequence ID to coordinates, and back

`get_coordinates_from_sequence_id` returns where a contig lies in the concatenated sequence.

`get_sequence_id_from_start_coordinate` does the opposite: given a position, it finds the contig containing it with a binary search, in O(log n) time.

In [13]:
print(seq_ds.get_coordinates_from_sequence_id(1))        # (30, 55)

for position in [0, 29, 30, 54, 55, 74]:
    print(position, "->", seq_ds.get_sequence_id_from_start_coordinate(position))

(30, 54)
0 -> 0
29 -> 0
30 -> 1
54 -> 2
55 -> 2
74 -> 3

### Extracting a region

`get_sequence_from_metadata` takes coordinates **relative to the contig** (not to the concatenated sequence) and an orientation:

- `forward`: the sequence as stored
- `backward`: its reverse complement (complement each base, then reverse)

Try changing the IDs and coordinates!

In [14]:
fwd = seq_ds.get_sequence_from_metadata(0, 0, 10, "forward")
bwd = seq_ds.get_sequence_from_metadata(0, 0, 10, "reverse")

print("forward :", fwd)   # TCTCGACCCG
print("reverse:", bwd)   # CGGGTCGAGA

assert bwd == seq_ds.reverse_complement(fwd)

forward : TCTCGACCCG
reverse: CGGGTCGAGA

Asking for coordinates outside the contig raises an error instead of silently returning bases from another contig:

In [15]:
try:
    seq_ds.get_sequence_from_metadata(
        sequence_id=2, # contig 2 is only 20 nt long
        start_coor=0,
        end_coor=50,
        orientation="forward"
    )
except ValueError as e:
    print("ValueError:", e)

ValueError: Coordinates 0-50 are out of bounds for sequence ID 2 with sequence length 20. (The coordinates were mapped to 54-104 with full sequence length 115.)

## 4. Looking up embeddings

A language model like ProkBERT does not see nucleotides directly but **tokens**. With LCA tokenization, k-mers of size `k` are taken at every `shift`-th position, so a sequence of length `L` gives

$$N = \left\lfloor \frac{L - k}{s} \right\rfloor + 1$$

k-mers, plus the special tokens `[CLS]` and `[SEP]`.

For example, `AAGTCCAGGATC` with `k = 6`, `shift = 2` gives `AAGTCC`, `GTCCAG`, `CCAGGA`, `AGGATC`.

In [16]:
print(EmbeddingDataset.calculate_lca_num_tokens(12, 6, 2, special_tokens=0))  # 4
print(EmbeddingDataset.calculate_lca_num_tokens(12, 6, 2))                    # 6, with [CLS] and [SEP]

4
6

### Creating embedding

Real embeddings come the actual model. Here we create a **fake** embedding 
from the test dataset.

The config describes how the embedding was produced (k-mer, shift, pooling, special tokens).

In [17]:
# uncomment and run this script
# !python3 /home/osvathm/prokbert/scripts/embed_dataset.py \
#     --model neuralbioinfo/prokbert-mini-long \
#     --input-dir /home/osvathm/prokbert/examples/outputs/toy_example/ \
#     --output-dir /home/osvathm/prokbert/examples/outputs/toy_example \
#     --seq-len 4 \
#     --pooling-len 2 \
#     --batch-size 4 \
#     --kmer 6 \
#     --shift 2 \
#     --verbose

The embeddings are loaded with **memory mapping**: rows are read from disk only when accessed, so even very large embedding files fit.

Now we ask for the embedding of a contig region, using contig-relative coordinates, just like with sequences:

In [57]:
from prokbert.sequence_dataset import EmbeddingDataset

emb_ds = EmbeddingDataset(
    sequence_dataset=seq_ds,
    config_path=f"{SAVE_DIR}/config.yaml",
    embedding_file=f"{SAVE_DIR}/embeddings_forward.pt",
    seq_tokens_file=f"{SAVE_DIR}/seq_tokens.pt",
)
emb_ds.config

{'tokenizer': 'LCATokenizer',
 'kmer': 6,
 'shift': 2,
 'model': 'neuralbioinfo/prokbert-mini-long',
 'pooling_strategy': 'mean',
 'pooling_length': 2,
 'special_tokens': []}

In [58]:
pd.DataFrame(seq_ds.metadata)

,genome_id,contig_id,sequence_id,coordinate,orientation,description,label
0,None,OM913597.1,0,"(0, 30)",forward,"OM913597.1 Aeromonas phage vB_AspA_Bolek, synt...",None
1,None,OM913598.1,1,"(30, 54)",forward,"OM913598.1 Aeromonas phage vB_AspA_Lolek, synt...",None
2,None,OM913599.1,2,"(54, 74)",forward,"OM913599.1 Aeromonas phage vB_AspA_Tola, synth...",None
3,None,OQ832096.1,3,"(74, 95)",forward,"OQ832096.1 Halomonas phage vB_HmeY_H4907, synt...",None
4,None,JX507079.1,4,"(95, 115)",forward,"JX507079.1 Acidithiobacillus phage AcaML1, syn...",None

In [59]:
emb_ds.seq_tokens, emb_ds.seq_tokens.shape, emb_ds.embedding.shape

(tensor([13, 10,  8,  8,  8]), torch.Size([5]), torch.Size([24, 384]))

In [60]:
emb_ds.seq_rows, emb_ds.row_offsets

(tensor([7, 5, 4, 4, 4]), tensor([ 0,  7, 12, 16, 20]))

In [61]:
for i, sequence_id in enumerate(range(len(seq_ds.metadata))):
    start, end = seq_ds.get_coordinates_from_sequence_id(sequence_id)

    emb = emb_ds.get_embedding_from_sequence_id_with_relative_coordinates(
        sequence_id, 0, end - start
    )

DEBUG:root:Sequence ID 0: absolute 0-30, requested relative 0-30
DEBUG:root:Tokens within contig: 0-13 (of 13 tokens)
DEBUG:root:Rows within contig: 0-7 (of 7), rows in embedding tensor: 0-7 (offset 0)
DEBUG:root:Sequence ID 1: absolute 30-54, requested relative 0-24
DEBUG:root:Tokens within contig: 0-10 (of 10 tokens)
DEBUG:root:Rows within contig: 0-5 (of 5), rows in embedding tensor: 7-12 (offset 7)
DEBUG:root:Sequence ID 2: absolute 54-74, requested relative 0-20
DEBUG:root:Tokens within contig: 0-8 (of 8 tokens)
DEBUG:root:Rows within contig: 0-4 (of 4), rows in embedding tensor: 12-16 (offset 12)
DEBUG:root:Sequence ID 3: absolute 74-95, requested relative 0-21
DEBUG:root:Tokens within contig: 0-8 (of 8 tokens)
DEBUG:root:Rows within contig: 0-4 (of 4), rows in embedding tensor: 16-20 (offset 16)
DEBUG:root:Sequence ID 4: absolute 95-115, requested relative 0-20
DEBUG:root:Tokens within contig: 0-8 (of 8 tokens)
DEBUG:root:Rows within contig: 0-4 (of 4), rows in embedding tensor: 20-24 (offset 20)

In [62]:
embeds = emb_ds.get_embedding_from_sequence_id_with_relative_coordinates(0, 10, 20)
embeds.shape

DEBUG:root:Sequence ID 0: absolute 0-30, requested relative 10-20
DEBUG:root:Tokens within contig: 3-10 (of 13 tokens)
DEBUG:root:Rows within contig: 1-5 (of 7), rows in embedding tensor: 1-5 (offset 0)

torch.Size([4, 384])

##### Minimal Example

Python's zero-based indexing and its treatment of list ranges as half-open intervals (closed on the left, open on the right) can make the interpretation difficult, so let's look at a minimal example.

Let the sequence length be 12, the k-mer size 6, the shift 2, and the pooling size 2.

Using the `LCATokenizer`, we split the following example sequence into the following 4 tokens:

In [63]:
# index:     0   1   2   3   4   5   6   7   8   9   10  11
#            A   A   G   T   C   C   A   G   G   A   T   C

# token 0    A   A   G   T   C   C                              [0, 6)
# token 1            G   T   C   C   A   G                      [2, 8)
# token 2                    C   C   A   G   G   A              [4, 10)
# token 3                            A   G   G   A   T   C      [6, 12)

In [64]:
def calculate_lca_num_tokens(seq_len: int, kmer: int, shift: int) -> int:
    if seq_len < kmer: return 0
    return (seq_len - kmer) // shift + 1

In [65]:
# set the parameters
seq_len = 12
kmer = 6
shift = 2
pool = 2                    # pooling len
n_rows = 2                  # there is 4 tokens, so we get 2 (embedding) rows
num_tokens = 4              # number of tokens

In [66]:
# requested relative start and end positions in the sequence
rel_start, rel_end = 8, 11

In [67]:
start_token = calculate_lca_num_tokens(rel_start, kmer, shift)
end_token = min(num_tokens, math.ceil((rel_end) / shift))

print(start_token, end_token)

2 4

In [68]:
start = math.floor(start_token / pool)
end = min(math.ceil(end_token / pool), n_rows)

print(start, end)

1 2

# 5. Sampling segments

A language model can only read a limited number of tokens at once, so long contigs are cut into shorter **segments** before tokenization. Two datasets decide *where* the segments are: `ContiguousSegmentDataset` and `RandomSegmentDataset`. By default they yield only coordinates, so they are cheap even for whole genomes.

Each segment has:

- `segment_id`: the segment's number
- `sequence_id`, `contig_id`, `genome_id`, `orientation`: which contig it comes from
- `absolute_coordinate`: `(start, end)` in the **concatenated** sequence
- `relative_coordinate`: `(start, end)` inside the contig

Both are left-closed, right-open `[start, end)`, like Python slicing.

Two parameters control the segment length:

- `max_segment_length`: the longest allowed segment
- `min_segment_length`: shorter segments are dropped, because they carry too little context

In [69]:
from prokbert.dataset import RandomSegmentDataset, ContiguousSegmentDataset

In [70]:
# check metadata again
helper.convert_to(seq_ds.metadata)

,genome_id,contig_id,sequence_id,coordinate,orientation,description,label
0,None,OM913597.1,0,"(0, 30)",forward,"OM913597.1 Aeromonas phage vB_AspA_Bolek, synt...",None
1,None,OM913598.1,1,"(30, 54)",forward,"OM913598.1 Aeromonas phage vB_AspA_Lolek, synt...",None
2,None,OM913599.1,2,"(54, 74)",forward,"OM913599.1 Aeromonas phage vB_AspA_Tola, synth...",None
3,None,OQ832096.1,3,"(74, 95)",forward,"OQ832096.1 Halomonas phage vB_HmeY_H4907, synt...",None
4,None,JX507079.1,4,"(95, 115)",forward,"JX507079.1 Acidithiobacillus phage AcaML1, syn...",None

## Sequence Segmentation

### Contiguous segmentation

Each contig is cut into consecutive, disjoint chunks of `max_segment_length`, starting at the beginning of the contig: `[0, 10)`, `[10, 20)`, ... Every position is covered exactly once, except for a short remainder at the end of a contig, which is dropped if it is shorter than `min_segment_length`.

`segment_id` is deterministic: the same segment always gets the same ID, no matter how many times you iterate or how many DataLoader workers you use.

In [71]:
contiguous_dataset = ContiguousSegmentDataset(
    sequence_dataset=seq_ds,
    min_segment_length=5,
    max_segment_length=10,
    return_sequence=False # set to True to see the actual sequence
)

In [72]:
for segment in iter(contiguous_dataset):
    print(segment)

{'segment_id': 0, 'contig_id': 'OM913597.1', 'genome_id': None, 'sequence_id': 0, 'absolute_coordinate': (0, 10), 'relative_coordinate': (0, 10), 'orientation': 'forward', 'label': None}
{'segment_id': 1, 'contig_id': 'OM913597.1', 'genome_id': None, 'sequence_id': 0, 'absolute_coordinate': (10, 20), 'relative_coordinate': (10, 20), 'orientation': 'forward', 'label': None}
{'segment_id': 2, 'contig_id': 'OM913597.1', 'genome_id': None, 'sequence_id': 0, 'absolute_coordinate': (20, 30), 'relative_coordinate': (20, 30), 'orientation': 'forward', 'label': None}
{'segment_id': 3, 'contig_id': 'OM913598.1', 'genome_id': None, 'sequence_id': 1, 'absolute_coordinate': (30, 40), 'relative_coordinate': (0, 10), 'orientation': 'forward', 'label': None}
{'segment_id': 4, 'contig_id': 'OM913598.1', 'genome_id': None, 'sequence_id': 1, 'absolute_coordinate': (40, 50), 'relative_coordinate': (10, 20), 'orientation': 'forward', 'label': None}
{'segment_id': 5, 'contig_id': 'OM913599.1', 'genome_id': None, 'sequence_id': 2, 'absolute_coordinate': (54, 64), 'relative_coordinate': (0, 10), 'orientation': 'forward', 'label': None}
{'segment_id': 6, 'contig_id': 'OM913599.1', 'genome_id': None, 'sequence_id': 2, 'absolute_coordinate': (64, 74), 'relative_coordinate': (10, 20), 'orientation': 'forward', 'label': None}
{'segment_id': 7, 'contig_id': 'OQ832096.1', 'genome_id': None, 'sequence_id': 3, 'absolute_coordinate': (74, 84), 'relative_coordinate': (0, 10), 'orientation': 'forward', 'label': None}
{'segment_id': 8, 'contig_id': 'OQ832096.1', 'genome_id': None, 'sequence_id': 3, 'absolute_coordinate': (84, 94), 'relative_coordinate': (10, 20), 'orientation': 'forward', 'label': None}
{'segment_id': 9, 'contig_id': 'JX507079.1', 'genome_id': None, 'sequence_id': 4, 'absolute_coordinate': (95, 105), 'relative_coordinate': (0, 10), 'orientation': 'forward', 'label': None}
{'segment_id': 10, 'contig_id': 'JX507079.1', 'genome_id': None, 'sequence_id': 4, 'absolute_coordinate': (105, 115), 'relative_coordinate': (10, 20), 'orientation': 'forward', 'label': None}

### Random segmentation

The other option is random segmentation. It is an **infinite stream**: the dataset keeps producing new random segments for as long as you ask for them, so you decide how many to take. Each segment is made in two steps:

1. **Choose a contig.** A position is drawn uniformly from the whole concatenated sequence, and the contig containing it is chosen. This way, longer contigs are picked proportionally more often.
2. **Choose the segment inside the contig**, depending on the contig's length:
   - longer than `max_segment_length`: a start position is drawn uniformly so that the whole segment fits inside the contig, and the segment is exactly `max_segment_length` long;
   - between `min_segment_length` and `max_segment_length`: the whole contig is returned as one segment;
   - shorter than `min_segment_length`: the contig is skipped, and a new position is drawn.

Segments never cross the boundary between two contigs, and their length is always between `min_segment_length` and `max_segment_length`.

The same region can be drawn more than once, so here `segment_id` numbers the *draws*, not the regions. It starts from 0 every time you start iterating, and it stays unique across DataLoader workers.

⚠️ Because the stream never ends, `list(random_dataset)` or a plain `for` loop without a `break` would run forever. Always limit the number of segments, e.g. with `itertools.islice`.

Run the next cell several times: the segments change every time.

In [73]:
random_dataset = RandomSegmentDataset(
    sequence_dataset=seq_ds,
    min_segment_length=5,
    max_segment_length=10,
    return_sequence=False
)

In [74]:
for i, segment in enumerate(iter(random_dataset)):
    if i >= 15: break
    print(segment)

{'segment_id': 0, 'contig_id': 'OM913597.1', 'genome_id': None, 'sequence_id': 0, 'absolute_coordinate': (15, 25), 'relative_coordinate': (15, 25), 'orientation': 'forward', 'label': None}
{'segment_id': 1, 'contig_id': 'OM913599.1', 'genome_id': None, 'sequence_id': 2, 'absolute_coordinate': (55, 65), 'relative_coordinate': (1, 11), 'orientation': 'forward', 'label': None}
{'segment_id': 2, 'contig_id': 'OM913599.1', 'genome_id': None, 'sequence_id': 2, 'absolute_coordinate': (59, 69), 'relative_coordinate': (5, 15), 'orientation': 'forward', 'label': None}
{'segment_id': 3, 'contig_id': 'OM913597.1', 'genome_id': None, 'sequence_id': 0, 'absolute_coordinate': (9, 19), 'relative_coordinate': (9, 19), 'orientation': 'forward', 'label': None}
{'segment_id': 4, 'contig_id': 'OM913597.1', 'genome_id': None, 'sequence_id': 0, 'absolute_coordinate': (4, 14), 'relative_coordinate': (4, 14), 'orientation': 'forward', 'label': None}
{'segment_id': 5, 'contig_id': 'OM913599.1', 'genome_id': None, 'sequence_id': 2, 'absolute_coordinate': (58, 68), 'relative_coordinate': (4, 14), 'orientation': 'forward', 'label': None}
{'segment_id': 6, 'contig_id': 'OM913597.1', 'genome_id': None, 'sequence_id': 0, 'absolute_coordinate': (18, 28), 'relative_coordinate': (18, 28), 'orientation': 'forward', 'label': None}
{'segment_id': 7, 'contig_id': 'OM913597.1', 'genome_id': None, 'sequence_id': 0, 'absolute_coordinate': (4, 14), 'relative_coordinate': (4, 14), 'orientation': 'forward', 'label': None}
{'segment_id': 8, 'contig_id': 'OM913598.1', 'genome_id': None, 'sequence_id': 1, 'absolute_coordinate': (43, 53), 'relative_coordinate': (13, 23), 'orientation': 'forward', 'label': None}
{'segment_id': 9, 'contig_id': 'OM913599.1', 'genome_id': None, 'sequence_id': 2, 'absolute_coordinate': (54, 64), 'relative_coordinate': (0, 10), 'orientation': 'forward', 'label': None}
{'segment_id': 10, 'contig_id': 'OM913597.1', 'genome_id': None, 'sequence_id': 0, 'absolute_coordinate': (17, 27), 'relative_coordinate': (17, 27), 'orientation': 'forward', 'label': None}
{'segment_id': 11, 'contig_id': 'OM913598.1', 'genome_id': None, 'sequence_id': 1, 'absolute_coordinate': (33, 43), 'relative_coordinate': (3, 13), 'orientation': 'forward', 'label': None}
{'segment_id': 12, 'contig_id': 'OM913597.1', 'genome_id': None, 'sequence_id': 0, 'absolute_coordinate': (16, 26), 'relative_coordinate': (16, 26), 'orientation': 'forward', 'label': None}
{'segment_id': 13, 'contig_id': 'OM913597.1', 'genome_id': None, 'sequence_id': 0, 'absolute_coordinate': (1, 11), 'relative_coordinate': (1, 11), 'orientation': 'forward', 'label': None}
{'segment_id': 14, 'contig_id': 'OM913599.1', 'genome_id': None, 'sequence_id': 2, 'absolute_coordinate': (54, 64), 'relative_coordinate': (0, 10), 'orientation': 'forward', 'label': None}

#### Reading the sequence

With `return_sequence=True` both datasets also read the sequence of each segment and add it under the `"sequence"` key. The coordinates and IDs stay the same, so you always know where a sequence comes from.

In [75]:
# dataset = ContiguousSegmentDataset(
#     sequence_dataset=seq_ds,
#     min_segment_length=5,
#     max_segment_length=10,
#     return_sequence=True
# )
dataset = RandomSegmentDataset(
    sequence_dataset=seq_ds,
    min_segment_length=5,
    max_segment_length=10,
    return_sequence=True,
)

for i, segment in enumerate(iter(dataset)):
    if i >= 15: break
    print(segment)

{'segment_id': 0, 'contig_id': 'OQ832096.1', 'genome_id': None, 'sequence_id': 3, 'absolute_coordinate': (78, 88), 'relative_coordinate': (4, 14), 'orientation': 'forward', 'label': None, 'sequence': 'NACGTNGGAT'}
{'segment_id': 1, 'contig_id': 'JX507079.1', 'genome_id': None, 'sequence_id': 4, 'absolute_coordinate': (103, 113), 'relative_coordinate': (8, 18), 'orientation': 'forward', 'label': None, 'sequence': 'GCCTCGCCTC'}
{'segment_id': 2, 'contig_id': 'OM913598.1', 'genome_id': None, 'sequence_id': 1, 'absolute_coordinate': (42, 52), 'relative_coordinate': (12, 22), 'orientation': 'forward', 'label': None, 'sequence': 'CCACCGCAAC'}
{'segment_id': 3, 'contig_id': 'OM913599.1', 'genome_id': None, 'sequence_id': 2, 'absolute_coordinate': (63, 73), 'relative_coordinate': (9, 19), 'orientation': 'forward', 'label': None, 'sequence': 'CCTCGCTTTC'}
{'segment_id': 4, 'contig_id': 'OM913597.1', 'genome_id': None, 'sequence_id': 0, 'absolute_coordinate': (17, 27), 'relative_coordinate': (17, 27), 'orientation': 'forward', 'label': None, 'sequence': 'GCAATCGCCC'}
{'segment_id': 5, 'contig_id': 'OM913599.1', 'genome_id': None, 'sequence_id': 2, 'absolute_coordinate': (60, 70), 'relative_coordinate': (6, 16), 'orientation': 'forward', 'label': None, 'sequence': 'TCGCCTCGCT'}
{'segment_id': 6, 'contig_id': 'JX507079.1', 'genome_id': None, 'sequence_id': 4, 'absolute_coordinate': (98, 108), 'relative_coordinate': (3, 13), 'orientation': 'forward', 'label': None, 'sequence': 'TACTCGCCTC'}
{'segment_id': 7, 'contig_id': 'OM913598.1', 'genome_id': None, 'sequence_id': 1, 'absolute_coordinate': (40, 50), 'relative_coordinate': (10, 20), 'orientation': 'forward', 'label': None, 'sequence': 'CCCCACCGCA'}
{'segment_id': 8, 'contig_id': 'OM913597.1', 'genome_id': None, 'sequence_id': 0, 'absolute_coordinate': (9, 19), 'relative_coordinate': (9, 19), 'orientation': 'forward', 'label': None, 'sequence': 'GTCCCACCGC'}
{'segment_id': 9, 'contig_id': 'OM913598.1', 'genome_id': None, 'sequence_id': 1, 'absolute_coordinate': (37, 47), 'relative_coordinate': (7, 17), 'orientation': 'forward', 'label': None, 'sequence': 'CCGCCCCACC'}
{'segment_id': 10, 'contig_id': 'OQ832096.1', 'genome_id': None, 'sequence_id': 3, 'absolute_coordinate': (82, 92), 'relative_coordinate': (8, 18), 'orientation': 'forward', 'label': None, 'sequence': 'TNGGATCCTT'}
{'segment_id': 11, 'contig_id': 'OM913598.1', 'genome_id': None, 'sequence_id': 1, 'absolute_coordinate': (43, 53), 'relative_coordinate': (13, 23), 'orientation': 'forward', 'label': None, 'sequence': 'CACCGCAACC'}
{'segment_id': 12, 'contig_id': 'JX507079.1', 'genome_id': None, 'sequence_id': 4, 'absolute_coordinate': (97, 107), 'relative_coordinate': (2, 12), 'orientation': 'forward', 'label': None, 'sequence': 'TTACTCGCCT'}
{'segment_id': 13, 'contig_id': 'OQ832096.1', 'genome_id': None, 'sequence_id': 3, 'absolute_coordinate': (82, 92), 'relative_coordinate': (8, 18), 'orientation': 'forward', 'label': None, 'sequence': 'TNGGATCCTT'}
{'segment_id': 14, 'contig_id': 'OM913599.1', 'genome_id': None, 'sequence_id': 2, 'absolute_coordinate': (63, 73), 'relative_coordinate': (9, 19), 'orientation': 'forward', 'label': None, 'sequence': 'CCTCGCTTTC'}

## Embedding Segmentation

In [111]:
logging.basicConfig(level=logging.WARNING, force=True)

### Contiguous segmentation

In [117]:
contiguous_dataset = ContiguousSegmentDataset(
    sequence_dataset=seq_ds,
    min_segment_length=5,
    max_segment_length=10,
    embedding_dataset=emb_ds,
    return_embedding=True
)

In [118]:
for segment in iter(contiguous_dataset):
    print(segment)
    print(segment["embedding"].shape)

{'segment_id': 0, 'contig_id': 'OM913597.1', 'genome_id': None, 'sequence_id': 0, 'absolute_coordinate': (0, 10), 'relative_coordinate': (0, 10), 'orientation': 'forward', 'label': None, 'embedding': tensor([[-0.5277,  2.0918,  1.4820,  ...,  0.1325, -0.4465,  2.0704],
        [ 0.2498,  2.0988, -1.0205,  ..., -0.2105, -0.3701,  0.7268],
        [-0.6518,  1.9225, -0.9459,  ..., -0.9993,  0.2974,  0.9294]])}
torch.Size([3, 384])
{'segment_id': 1, 'contig_id': 'OM913597.1', 'genome_id': None, 'sequence_id': 0, 'absolute_coordinate': (10, 20), 'relative_coordinate': (10, 20), 'orientation': 'forward', 'label': None, 'embedding': tensor([[ 0.2498,  2.0988, -1.0205,  ..., -0.2105, -0.3701,  0.7268],
        [-0.6518,  1.9225, -0.9459,  ..., -0.9993,  0.2974,  0.9294],
        [ 0.0577,  2.9478, -1.2927,  ..., -1.4562,  0.0523,  0.9259],
        [-0.3916,  1.6891, -0.1671,  ..., -0.6627, -1.1462,  0.2008]])}
torch.Size([4, 384])
{'segment_id': 2, 'contig_id': 'OM913597.1', 'genome_id': None, 'sequence_id': 0, 'absolute_coordinate': (20, 30), 'relative_coordinate': (20, 30), 'orientation': 'forward', 'label': None, 'embedding': tensor([[-0.3916,  1.6891, -0.1671,  ..., -0.6627, -1.1462,  0.2008],
        [-1.2122,  1.0731, -0.2568,  ..., -0.5988,  0.0848,  1.9862],
        [ 0.4974,  3.2971, -1.7518,  ...,  0.5225,  0.1500,  1.3982]])}
torch.Size([3, 384])
{'segment_id': 3, 'contig_id': 'OM913598.1', 'genome_id': None, 'sequence_id': 1, 'absolute_coordinate': (30, 40), 'relative_coordinate': (0, 10), 'orientation': 'forward', 'label': None, 'embedding': tensor([[-0.6902,  1.9452,  1.4387,  ...,  0.3193, -0.5581,  1.7416],
        [ 0.2035,  2.0269, -1.0743,  ..., -0.0682, -0.3548,  0.7948],
        [-0.1764,  2.3499, -1.9607,  ..., -0.8919,  1.3905,  0.7906]])}
torch.Size([3, 384])
{'segment_id': 4, 'contig_id': 'OM913598.1', 'genome_id': None, 'sequence_id': 1, 'absolute_coordinate': (40, 50), 'relative_coordinate': (10, 20), 'orientation': 'forward', 'label': None, 'embedding': tensor([[ 0.2035,  2.0269, -1.0743,  ..., -0.0682, -0.3548,  0.7948],
        [-0.1764,  2.3499, -1.9607,  ..., -0.8919,  1.3905,  0.7906],
        [-0.0345,  3.1461, -1.5356,  ..., -1.2770,  0.2557,  0.8263],
        [-0.5842,  2.8566,  0.6106,  ..., -1.3432, -0.5221,  0.8480]])}
torch.Size([4, 384])
{'segment_id': 5, 'contig_id': 'OM913599.1', 'genome_id': None, 'sequence_id': 2, 'absolute_coordinate': (54, 64), 'relative_coordinate': (0, 10), 'orientation': 'forward', 'label': None, 'embedding': tensor([[-0.5858,  0.0634, -1.1475,  ..., -0.9602, -0.5479,  0.7308],
        [-0.6555,  0.4694, -0.8784,  ..., -0.2981, -0.6979,  1.0449],
        [-1.1088,  0.4293, -0.4216,  ..., -0.0342, -2.0613,  1.3974]])}
torch.Size([3, 384])
{'segment_id': 6, 'contig_id': 'OM913599.1', 'genome_id': None, 'sequence_id': 2, 'absolute_coordinate': (64, 74), 'relative_coordinate': (10, 20), 'orientation': 'forward', 'label': None, 'embedding': tensor([[-0.6555,  0.4694, -0.8784,  ..., -0.2981, -0.6979,  1.0449],
        [-1.1088,  0.4293, -0.4216,  ..., -0.0342, -2.0613,  1.3974],
        [-0.7895,  1.1389, -2.0086,  ..., -0.4630, -1.0015,  0.6172]])}
torch.Size([3, 384])
{'segment_id': 7, 'contig_id': 'OQ832096.1', 'genome_id': None, 'sequence_id': 3, 'absolute_coordinate': (74, 84), 'relative_coordinate': (0, 10), 'orientation': 'forward', 'label': None, 'embedding': tensor([[ 0.7777,  0.1036, -0.9848,  ..., -0.3717, -0.6135,  1.1531],
        [ 0.7721,  0.1018, -0.9860,  ..., -0.3679, -0.6161,  1.1523],
        [-1.5537,  0.3567, -0.2338,  ..., -0.6447, -0.5834,  0.9492]])}
torch.Size([3, 384])
{'segment_id': 8, 'contig_id': 'OQ832096.1', 'genome_id': None, 'sequence_id': 3, 'absolute_coordinate': (84, 94), 'relative_coordinate': (10, 20), 'orientation': 'forward', 'label': None, 'embedding': tensor([[ 0.7721,  0.1018, -0.9860,  ..., -0.3679, -0.6161,  1.1523],
        [-1.5537,  0.3567, -0.2338,  ..., -0.6447, -0.5834,  0.9492],
        [-0.6415,  0.7436,  0.0881,  ..., -0.7059, -1.2766,  1.3420]])}
torch.Size([3, 384])
{'segment_id': 9, 'contig_id': 'JX507079.1', 'genome_id': None, 'sequence_id': 4, 'absolute_coordinate': (95, 105), 'relative_coordinate': (0, 10), 'orientation': 'forward', 'label': None, 'embedding': tensor([[-1.0500,  1.2031,  0.2783,  ...,  0.0842,  0.0642, -0.2692],
        [-0.2558,  1.0106, -0.3473,  ..., -0.3639, -0.9447,  0.5760],
        [-1.4501,  0.3304, -0.6326,  ..., -0.1820, -2.0309,  1.5112]])}
torch.Size([3, 384])
{'segment_id': 10, 'contig_id': 'JX507079.1', 'genome_id': None, 'sequence_id': 4, 'absolute_coordinate': (105, 115), 'relative_coordinate': (10, 20), 'orientation': 'forward', 'label': None, 'embedding': tensor([[-0.2558,  1.0106, -0.3473,  ..., -0.3639, -0.9447,  0.5760],
        [-1.4501,  0.3304, -0.6326,  ..., -0.1820, -2.0309,  1.5112],
        [-0.6903,  0.1567, -0.0722,  ..., -1.1343, -0.4942,  0.9553]])}
torch.Size([3, 384])

### Random segmentation

In [79]:
random_dataset = RandomSegmentDataset(
    sequence_dataset=seq_ds,
    min_segment_length=5,
    max_segment_length=10,
    embedding_dataset=emb_ds,
    return_embedding=True
    )

In [80]:
for i, segment in enumerate(iter(random_dataset)):
    if i >= 5: break
    print(segment)

{'segment_id': 0, 'contig_id': 'OM913598.1', 'genome_id': None, 'sequence_id': 1, 'absolute_coordinate': (31, 41), 'relative_coordinate': (1, 11), 'orientation': 'forward', 'label': None, 'embedding': tensor([[-0.6902,  1.9452,  1.4387,  ...,  0.3193, -0.5581,  1.7416],
        [ 0.2035,  2.0269, -1.0743,  ..., -0.0682, -0.3548,  0.7948],
        [-0.1764,  2.3499, -1.9607,  ..., -0.8919,  1.3905,  0.7906]])}
{'segment_id': 1, 'contig_id': 'OM913597.1', 'genome_id': None, 'sequence_id': 0, 'absolute_coordinate': (8, 18), 'relative_coordinate': (8, 18), 'orientation': 'forward', 'label': None, 'embedding': tensor([[ 0.2498,  2.0988, -1.0205,  ..., -0.2105, -0.3701,  0.7268],
        [-0.6518,  1.9225, -0.9459,  ..., -0.9993,  0.2974,  0.9294],
        [ 0.0577,  2.9478, -1.2927,  ..., -1.4562,  0.0523,  0.9259],
        [-0.3916,  1.6891, -0.1671,  ..., -0.6627, -1.1462,  0.2008]])}
{'segment_id': 2, 'contig_id': 'OQ832096.1', 'genome_id': None, 'sequence_id': 3, 'absolute_coordinate': (81, 91), 'relative_coordinate': (7, 17), 'orientation': 'forward', 'label': None, 'embedding': tensor([[ 0.7777,  0.1036, -0.9848,  ..., -0.3717, -0.6135,  1.1531],
        [ 0.7721,  0.1018, -0.9860,  ..., -0.3679, -0.6161,  1.1523],
        [-1.5537,  0.3567, -0.2338,  ..., -0.6447, -0.5834,  0.9492],
        [-0.6415,  0.7436,  0.0881,  ..., -0.7059, -1.2766,  1.3420]])}
{'segment_id': 3, 'contig_id': 'JX507079.1', 'genome_id': None, 'sequence_id': 4, 'absolute_coordinate': (102, 112), 'relative_coordinate': (7, 17), 'orientation': 'forward', 'label': None, 'embedding': tensor([[-1.0500,  1.2031,  0.2783,  ...,  0.0842,  0.0642, -0.2692],
        [-0.2558,  1.0106, -0.3473,  ..., -0.3639, -0.9447,  0.5760],
        [-1.4501,  0.3304, -0.6326,  ..., -0.1820, -2.0309,  1.5112],
        [-0.6903,  0.1567, -0.0722,  ..., -1.1343, -0.4942,  0.9553]])}
{'segment_id': 4, 'contig_id': 'OM913597.1', 'genome_id': None, 'sequence_id': 0, 'absolute_coordinate': (6, 16), 'relative_coordinate': (6, 16), 'orientation': 'forward', 'label': None, 'embedding': tensor([[-0.5277,  2.0918,  1.4820,  ...,  0.1325, -0.4465,  2.0704],
        [ 0.2498,  2.0988, -1.0205,  ..., -0.2105, -0.3701,  0.7268],
        [-0.6518,  1.9225, -0.9459,  ..., -0.9993,  0.2974,  0.9294],
        [ 0.0577,  2.9478, -1.2927,  ..., -1.4562,  0.0523,  0.9259]])}

## 6. Using the datasets with a PyTorch DataLoader


A `DataLoader` groups segments into batches and can produce them in parallel worker processes (`num_workers`).

PyTorch's default batching (`default_collate`) cannot handle segments as they are: `genome_id` is `None`, and the coordinate tuples would be split into separate tensors. So we pass `collate_fn=list`, which makes each batch a plain list of segment dicts.

In [137]:
from itertools import islice
from torch.utils.data import DataLoader

logging.basicConfig(level=logging.DEBUG, force=True)

loader = DataLoader(contiguous_dataset, batch_size=4, collate_fn=list)

for batch in loader:
    print(len(batch), [segment["segment_id"] for segment in batch])

DEBUG:root:Sequence ID 0: absolute 0-30, requested relative 0-10
DEBUG:root:Tokens within contig: 0-5 (of 13 tokens)
DEBUG:root:Rows within contig: 0-3 (of 7), rows in embedding tensor: 0-3 (offset 0)
DEBUG:root:Sequence ID 0: absolute 0-30, requested relative 10-20
DEBUG:root:Tokens within contig: 3-10 (of 13 tokens)
DEBUG:root:Rows within contig: 1-5 (of 7), rows in embedding tensor: 1-5 (offset 0)
DEBUG:root:Sequence ID 0: absolute 0-30, requested relative 20-30
DEBUG:root:Tokens within contig: 8-13 (of 13 tokens)
DEBUG:root:Rows within contig: 4-7 (of 7), rows in embedding tensor: 4-7 (offset 0)
DEBUG:root:Sequence ID 1: absolute 30-54, requested relative 0-10
DEBUG:root:Tokens within contig: 0-5 (of 10 tokens)
DEBUG:root:Rows within contig: 0-3 (of 5), rows in embedding tensor: 7-10 (offset 7)
DEBUG:root:Sequence ID 1: absolute 30-54, requested relative 10-20
DEBUG:root:Tokens within contig: 3-10 (of 10 tokens)
DEBUG:root:Rows within contig: 1-5 (of 5), rows in embedding tensor: 8-12 (offset 7)
DEBUG:root:Sequence ID 2: absolute 54-74, requested relative 0-10
DEBUG:root:Tokens within contig: 0-5 (of 8 tokens)
DEBUG:root:Rows within contig: 0-3 (of 4), rows in embedding tensor: 12-15 (offset 12)
DEBUG:root:Sequence ID 2: absolute 54-74, requested relative 10-20
DEBUG:root:Tokens within contig: 3-8 (of 8 tokens)
DEBUG:root:Rows within contig: 1-4 (of 4), rows in embedding tensor: 13-16 (offset 12)
DEBUG:root:Sequence ID 3: absolute 74-95, requested relative 0-10
DEBUG:root:Tokens within contig: 0-5 (of 8 tokens)
DEBUG:root:Rows within contig: 0-3 (of 4), rows in embedding tensor: 16-19 (offset 16)
DEBUG:root:Sequence ID 3: absolute 74-95, requested relative 10-20
DEBUG:root:Tokens within contig: 3-8 (of 8 tokens)
DEBUG:root:Rows within contig: 1-4 (of 4), rows in embedding tensor: 17-20 (offset 16)
DEBUG:root:Sequence ID 4: absolute 95-115, requested relative 0-10
DEBUG:root:Tokens within contig: 0-5 (of 8 tokens)
DEBUG:root:Rows within contig: 0-3 (of 4), rows in embedding tensor: 20-23 (offset 20)
DEBUG:root:Sequence ID 4: absolute 95-115, requested relative 10-20
DEBUG:root:Tokens within contig: 3-8 (of 8 tokens)
DEBUG:root:Rows within contig: 1-4 (of 4), rows in embedding tensor: 21-24 (offset 20)

4 [0, 1, 2, 3]
4 [4, 5, 6, 7]
3 [8, 9, 10]

### Multiple workers

With `num_workers > 0` every worker gets its own copy of the dataset. `ContiguousSegmentDataset` splits the contigs between the workers, so each segment is produced exactly once. The order changes, because the DataLoader takes batches from the workers in turn, but the set of segments is the same.

In [82]:
def collect_segment_ids(dataset, num_workers):
    loader = DataLoader(dataset, batch_size=4, num_workers=num_workers, collate_fn=list)
    return [segment["segment_id"] for batch in loader for segment in batch]

ids_single = collect_segment_ids(contiguous_dataset, num_workers=0)
ids_multi = collect_segment_ids(contiguous_dataset, num_workers=2)

print("1 process: ", ids_single)
print("2 workers: ", ids_multi)

assert ids_single == list(range(len(ids_single)))    # 0, 1, 2, ... in order
assert sorted(ids_multi) == ids_single               # same segments, no duplicates
print("OK")

DEBUG:root:Sequence ID 0: absolute 0-30, requested relative 0-10
DEBUG:root:Tokens within contig: 0-5 (of 13 tokens)
DEBUG:root:Rows within contig: 0-3 (of 7), rows in embedding tensor: 0-3 (offset 0)
DEBUG:root:Sequence ID 0: absolute 0-30, requested relative 10-20
DEBUG:root:Tokens within contig: 3-10 (of 13 tokens)
DEBUG:root:Rows within contig: 1-5 (of 7), rows in embedding tensor: 1-5 (offset 0)
DEBUG:root:Sequence ID 0: absolute 0-30, requested relative 20-30
DEBUG:root:Tokens within contig: 8-13 (of 13 tokens)
DEBUG:root:Rows within contig: 4-7 (of 7), rows in embedding tensor: 4-7 (offset 0)
DEBUG:root:Sequence ID 1: absolute 30-54, requested relative 0-10
DEBUG:root:Tokens within contig: 0-5 (of 10 tokens)
DEBUG:root:Rows within contig: 0-3 (of 5), rows in embedding tensor: 7-10 (offset 7)
DEBUG:root:Sequence ID 1: absolute 30-54, requested relative 10-20
DEBUG:root:Tokens within contig: 3-10 (of 10 tokens)
DEBUG:root:Rows within contig: 1-5 (of 5), rows in embedding tensor: 8-12 (offset 7)
DEBUG:root:Sequence ID 2: absolute 54-74, requested relative 0-10
DEBUG:root:Tokens within contig: 0-5 (of 8 tokens)
DEBUG:root:Rows within contig: 0-3 (of 4), rows in embedding tensor: 12-15 (offset 12)
DEBUG:root:Sequence ID 2: absolute 54-74, requested relative 10-20
DEBUG:root:Tokens within contig: 3-8 (of 8 tokens)
DEBUG:root:Rows within contig: 1-4 (of 4), rows in embedding tensor: 13-16 (offset 12)
DEBUG:root:Sequence ID 3: absolute 74-95, requested relative 0-10
DEBUG:root:Tokens within contig: 0-5 (of 8 tokens)
DEBUG:root:Rows within contig: 0-3 (of 4), rows in embedding tensor: 16-19 (offset 16)
DEBUG:root:Sequence ID 3: absolute 74-95, requested relative 10-20
DEBUG:root:Tokens within contig: 3-8 (of 8 tokens)
DEBUG:root:Rows within contig: 1-4 (of 4), rows in embedding tensor: 17-20 (offset 16)
DEBUG:root:Sequence ID 4: absolute 95-115, requested relative 0-10
DEBUG:root:Tokens within contig: 0-5 (of 8 tokens)
DEBUG:root:Rows within contig: 0-3 (of 4), rows in embedding tensor: 20-23 (offset 20)
DEBUG:root:Sequence ID 4: absolute 95-115, requested relative 10-20
DEBUG:root:Tokens within contig: 3-8 (of 8 tokens)
DEBUG:root:Rows within contig: 1-4 (of 4), rows in embedding tensor: 21-24 (offset 20)
DEBUG:root:Sequence ID 0: absolute 0-30, requested relative 0-10
DEBUG:root:Tokens within contig: 0-5 (of 13 tokens)
DEBUG:root:Rows within contig: 0-3 (of 7), rows in embedding tensor: 0-3 (offset 0)
DEBUG:root:Sequence ID 0: absolute 0-30, requested relative 10-20
DEBUG:root:Sequence ID 1: absolute 30-54, requested relative 0-10
DEBUG:root:Tokens within contig: 3-10 (of 13 tokens)
DEBUG:root:Rows within contig: 1-5 (of 7), rows in embedding tensor: 1-5 (offset 0)
DEBUG:root:Tokens within contig: 0-5 (of 10 tokens)
DEBUG:root:Sequence ID 0: absolute 0-30, requested relative 20-30
DEBUG:root:Rows within contig: 0-3 (of 5), rows in embedding tensor: 7-10 (offset 7)
DEBUG:root:Tokens within contig: 8-13 (of 13 tokens)
DEBUG:root:Sequence ID 1: absolute 30-54, requested relative 10-20
DEBUG:root:Rows within contig: 4-7 (of 7), rows in embedding tensor: 4-7 (offset 0)
DEBUG:root:Tokens within contig: 3-10 (of 10 tokens)
DEBUG:root:Sequence ID 2: absolute 54-74, requested relative 0-10
DEBUG:root:Rows within contig: 1-5 (of 5), rows in embedding tensor: 8-12 (offset 7)
DEBUG:root:Tokens within contig: 0-5 (of 8 tokens)
DEBUG:root:Sequence ID 3: absolute 74-95, requested relative 0-10
DEBUG:root:Rows within contig: 0-3 (of 4), rows in embedding tensor: 12-15 (offset 12)
DEBUG:root:Tokens within contig: 0-5 (of 8 tokens)
DEBUG:root:Sequence ID 2: absolute 54-74, requested relative 10-20
DEBUG:root:Rows within contig: 0-3 (of 4), rows in embedding tensor: 16-19 (offset 16)
DEBUG:root:Tokens within contig: 3-8 (of 8 tokens)
DEBUG:root:Sequence ID 3: absolute 74-95, requested relative 10-20
DEBUG:root:Rows within contig: 1-4 (of 4), rows in embedding tensor: 13-16 (offset 12)
DEBUG:root:Tokens within contig: 3-8 (of 8 tokens)
DEBUG:root:Rows within contig: 1-4 (of 4), rows in embedding tensor: 17-20 (offset 16)
DEBUG:root:Sequence ID 4: absolute 95-115, requested relative 0-10
DEBUG:root:Tokens within contig: 0-5 (of 8 tokens)
DEBUG:root:Rows within contig: 0-3 (of 4), rows in embedding tensor: 20-23 (offset 20)
DEBUG:root:Sequence ID 4: absolute 95-115, requested relative 10-20
DEBUG:root:Tokens within contig: 3-8 (of 8 tokens)
DEBUG:root:Rows within contig: 1-4 (of 4), rows in embedding tensor: 21-24 (offset 20)

1 process:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
2 workers:  [0, 1, 2, 5, 3, 4, 7, 8, 6, 9, 10]
OK

For `RandomSegmentDataset` the workers draw independently, and each worker uses its own range of `segment_id`s, so the IDs stay unique. Because the stream is infinite, we take only the first few batches with `islice`. We also check that every sequence matches its coordinates.

In [83]:
random_dataset = RandomSegmentDataset(
    sequence_dataset=seq_ds,
    min_segment_length=5,
    max_segment_length=10,
    return_sequence=True,
)
loader = DataLoader(random_dataset, batch_size=4, num_workers=2, collate_fn=list)

segments = [segment for batch in islice(loader, 10) for segment in batch]
ids = [segment["segment_id"] for segment in segments]
print(ids)

assert len(ids) == len(set(ids))   # unique across workers
assert all(s["sequence"] == random_dataset.read_sequence(*s["absolute_coordinate"]) for s in segments)
print("OK")

[0, 2, 4, 6, 1, 3, 5, 7, 8, 10, 12, 14, 9, 11, 13, 15, 16, 18, 20, 22, 17, 19, 21, 23, 24, 26, 28, 30, 25, 27, 29, 31, 32, 34, 36, 38, 33, 35, 37, 39]
OK

## 7. From segments to model input

The model needs token IDs, not strings. The data collator tokenizes the sequences of a batch and pads them to the same length. All segments here are `max_segment_length` long, so every row has the same number of tokens and no padding is needed.

In [ ]:
from prokbert.tokenizer import LCATokenizer
from prokbert.data_collator import SegmentDataCollator

In [188]:
tokenizer = LCATokenizer(kmer=6, shift=2)

Create a random segment dataset with and without embeddings

In [ ]:
random_dataset = RandomSegmentDataset(
    sequence_dataset=seq_ds,
    min_segment_length=5,
    max_segment_length=10,
    embedding_dataset=emb_ds,

    # use this to return tokens from segments (without embeddings)
    # return_sequence=True,

    # use this to return embeddings from segments (and embedding mask)
    return_embedding=True
)

collator = SegmentDataCollator(
    tokenizer=tokenizer,
    add_special_tokens=False,
    return_metadata=True,

    # use this to return tokens from segments (without embeddings)
    # has_embedding=False

    # use this to return embeddings from segments (and embedding mask)
    has_embedding=True
)
loader = DataLoader(random_dataset, batch_size=1, collate_fn=collator)

In [ ]:
next(iter(loader)) # return without embeddings

{'input_ids': tensor([[ 350, 1434, 2393]]),
 'attention_mask': tensor([[1, 1, 1]]),
 'segment_id': tensor([0]),
 'sequence_id': tensor([1]),
 'absolute_coordinate': tensor([[35, 45]])}

In [200]:
next(iter(loader)) # return with embeddings

{'embeddings': tensor([[[-0.6902,  1.9452,  1.4387,  ...,  0.3193, -0.5581,  1.7416],
          [ 0.2035,  2.0269, -1.0743,  ..., -0.0682, -0.3548,  0.7948],
          [-0.1764,  2.3499, -1.9607,  ..., -0.8919,  1.3905,  0.7906],
          [-0.0345,  3.1461, -1.5356,  ..., -1.2770,  0.2557,  0.8263]]]),
 'embedding_mask': tensor([[1, 1, 1, 1]]),
 'segment_id': tensor([0]),
 'sequence_id': tensor([1]),
 'absolute_coordinate': tensor([[33, 43]])}